# Generated by Django 4.1.5 on 2023-01-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('estoque', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('estoque_min', models.PositiveIntegerField(default=0, verbose_name='Estoque Min')),
                ('slug', models.SlugField(verbose_name='Atalho')),
            ],
        ),
    ]
